export const registerProjectMail = {
  to: "projects@hainan-infra.com",
  subject: "Project Registration Request",
  body: [
    "Hello Hainan Infrastructure Team,",
    "",
    "I would like to register a project for review.",
    "",
    "Project Name:",
    "Country / Region:",
    "Sector:",
    "Funding Target (USD):",
    "Expected Timeline:",
    "Company / Sponsor:",
    "Contact Person:",
    "Contact Email:",
    "Contact Phone:",
    "",
    "Project Summary:",
    "",
    "",
    "FIles are in attachment.",
    "",
    "Best regards,",
    "",
  ].join("\n"),
} as const;
