import LegalProse from "@/components/Legal/LegalProse";

/* eslint-disable react/no-unescaped-entities */

/**
 * PrivacyContent
 *
 * Full text of the Privacy Policy. Edit freely — all standard HTML elements
 * (h1–h3, p, ul, ol, li, strong, em, hr, small) are styled by LegalProse.
 */
export default function PrivacyContent() {
  return (
    <div className="max-w-4xl mx-auto p-6 md:p-8 space-y-4">
      <LegalProse>
      <div className="mb-8">
        <h1>Privacy Policy</h1>
        <small>Effective Date: March 2026</small>
      </div>

      <h2>§ 1. NO PERSONAL DATA COLLECTION</h2>
      <p>
        Hainan Infrastructure Partners operates a stateless architecture. We do not intentionally collect or store 
        personal identifiers, including names, email addresses, government ID numbers, physical addresses, or account 
        registrations.
      </p>

      <h2>§ 2. BLOCKCHAIN DATA</h2>
      <p>
        When you connect a wallet address to the Interface, your address and transactions are broadcast to public 
        blockchain networks. This information is publicly visible, immutable, and is not controlled, managed, or 
        stored by the Company.
      </p>

      <h2>§ 3. THIRD-PARTY INFRASTRUCTURE AND RELAY PROTOCOLS</h2>
      <p>
        Interaction with blockchain networks involves critical third-party providers. You expressly acknowledge that 
        utilizing wallet connection protocols (e.g., WalletConnect) requires your device to establish WebSocket 
        connections with centralized, third-party cloud relay servers. These independent third parties actively collect, 
        process, and log technical telemetry, including your Internet Protocol (IP) address, browser User-Agent, and 
        geographic location, to maintain network connectivity and comply with their own independent regulatory obligations 
        (including OFAC screening). The Company does not access, command, or store the server logs generated by these 
        third-party connection protocols.
      </p>

      <h2>§ 4. INVOLUNTARY INFRASTRUCTURE LOGS (NETWORK LAYER)</h2>
      <p>
        The Company’s proprietary codebase (the Application Layer) is strictly stateless and intentionally designed to 
        collect zero personal data. However, the Interface is hosted and routed via independent, third-party web 
        infrastructure, including GitHub-hosted delivery layers (e.g., GitHub Pages and related CDN/DNS routing), 
        as well as other network providers. You expressly acknowledge 
        that these underlying network providers may automatically log IP addresses, browser types, and routing metadata 
        to prevent Distributed Denial of Service (DDoS) attacks and maintain server stability. These logs are generated 
        involuntarily at the Network Layer. The Company does not actively configure, retrieve, monetize, or utilize these 
        raw network logs to track, profile, or identify users.
      </p>

      <h2>§ 5. COOKIES, LOCAL STORAGE, AND CONSENT CONTROLS</h2>
      <p>
        The Interface uses a minimal set of browser storage technologies (including localStorage and equivalent browser
        persistence) that are strictly required for core functionality, including wallet session continuity,
        legal/disclaimer acknowledgments, and cookie-consent preference storage. We do not currently deploy
        first-party behavioral advertising cookies.
      </p>
      <p>
        You acknowledge that independent third-party providers used by the Interface (including hosting, relay,
        RPC, and wallet infrastructure providers) may place or process their own technical identifiers and
        connection metadata under their independent policies when you use the Interface.
      </p>

      <h2>§ 6. RIGHT TO BE FORGOTTEN</h2>
      <p>
        Because we do not maintain personal data records, there is no stored user data for the Company to delete. Users 
        may stop interacting with the Interface at any time by disconnecting their wallet. The Company cannot delete 
        public on-chain data.
      </p>

      <h2>§ 7. PRC PIPL AND CROSS-BORDER DATA TRANSFERS</h2>
      <p>
        As a stateless application operating from the Hainan Free Trade Port, the Company does not collect, process, or 
        export "Personal Information" or "Important Data" as defined by the PRC Personal Information Protection Law 
        (PIPL) and the Data Security Law (DSL). Any involuntary network-layer routing of IP addresses by third-party 
        infrastructure providers does not constitute a regulated cross-border data transfer by the Company. Users 
        interacting with the Interface from outside the PRC acknowledge that public blockchain ledger entries do not 
        constitute cross-border data transfers subject to localized data localization mandates.
      </p>
      </LegalProse>
    </div>
  );
}
